services:
  - type: web
    name: barcode-to-qr-bot
    runtime: python
    repo: https://github.com/ТВОЙ_ЛОГИН/barcode-to-qr-bot
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app